name: GitHub-Profile-3D-Contrib

on:
  workflow_dispatch:

jobs:
  generate-github-profile-3d-contrib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./profile-3d-contrib/profile-night-rainbow.svg
      - name: Push the generated SVG
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
